MCU = atmega32u4

BOOTLOADER = qmk-dfu

EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no

ENCODER_ENABLE = yes
